version: "3.8"
services:
  spring-app:
    image: sanjeevas/spring-rest-app
    environment:
      - SPRING_PROFILES_ACTIVE=mysql # or h2, depending on which profile you want
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD} # Coming from AWS Secrets Manager or environment
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD} # Coming from AWS Secrets Manager or environment
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
